### ISSUE TITLE
tests in database

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#10]
@SuperVasya  - do we need to extend tests in database, what is the direction for this?

**Comment by SuperVasya** [comment]
@epogrebnyak for now we have following tests:
- Is POST request forbidden if API_TOKEN is not provided in request headers or URL params
- Uploading data
- GET request with validation for right body

Probably we should add test if API_TOKEN is provided, but it's wrong, how do you think?

Also I will add tests for CSV formatter from [custom_api](https://github.com/mini-kep/helpers/blob/master/custom_api.py)

**Comment by epogrebnyak** [comment]
Some notes on testing with a database

From <http://flask.pocoo.org/docs/0.12/testing/#the-testing-skeleton>:
```python 
import os
import flaskr
import unittest
import tempfile

class FlaskrTestCase(unittest.TestCase):

    def setUp(self):
        self.db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
        flaskr.app.testing = True
        self.app = flaskr.app.test_client()
        with flaskr.app.app_context():
            flaskr.init_db()

    def tearDown(self):
        os.close(self.db_fd)
        os.unlink(flaskr.app.config['DATABASE'])

if __name__ == '__main__':
    unittest.main()
```

From <https://pythonhosted.org/Flask-Testing/#testing-with-sqlalchemy>:
```python 
from flask_testing import TestCase

from myapp import create_app, db

class MyTest(TestCase):

    SQLALCHEMY_DATABASE_URI = "sqlite://"
    TESTING = True

    def create_app(self):

        # pass in test configuration
        return create_app(self)

    def setUp(self):

        db.create_all()

    def tearDown(self):

        db.session.remove()
        db.drop_all()
```

**Comment by epogrebnyak** [comment]
Testing goals:
- [ ] make tests run without ```sys.path``` tweaking
- [ ] use smaller tests dataset to populate test database
- [ ] allow standalone code in flask with a  test database
- [ ] cover all functionality with tests

**Comment by epogrebnyak** [comment]
Other tests to look at:
- <https://github.com/miguelgrinberg/flasky/tree/master/tests>
- <https://github.com/JackStouffer/cookiecutter-Flask-Foundation/tree/master/%7B%7Bcookiecutter.repo_name%7D%7D/tests>
- <https://github.com/mattshaffer11/flask-cookiecutter/tree/master/%7B%7Bcookiecutter.project_name%7D%7D/test>

**Comment by epogrebnyak** [comment]
https://github.com/mjhea0/flaskr-tdd/blob/master/app-test.py

**Comment by epogrebnyak** [comment]
Test discovery without tweaking of sys.path done at <https://github.com/mini-kep/db/commit/580ce9d0fc7cd325dd71b4eb5222fca372b5420f#commitcomment-24953062>, suggested as test sceleton for further tests.

**Comment by epogrebnyak** [comment]
<https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/tests/conftest.py>

<https://github.com/pallets/flask/tree/master/tests>

**Comment by epogrebnyak** [comment]
[https://stackoverflow.com/questions/46811342/flask-testing-configuration-in-config-py-vs-base-test-class](https://stackoverflow.com/questions/46811342/flask-testing-configuration-in-config-py-vs-base-test-class)

**Comment by epogrebnyak** [comment]
Base test added by 84f8971a056df741828f4c14d01696bef01c41d8: <https://github.com/mini-kep/db/blob/refactoring/tests2/test_basic.py>

```python
import unittest
from flask import current_app
from db import _app
from db import db as fsa_db

def make_app():
    app = _app() # was: Flask(__name__)
    app.testing = True
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///:memory:'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False        
    return app 

class BasicsTestCase(unittest.TestCase):
    def setUp(self):
        self.app = make_app()               
        self.app_context = self.app.app_context()
        self.app_context.push()
        fsa_db.init_app(app=self.app)
        fsa_db.create_all()

    def tearDown(self):
        fsa_db.session.remove()
        fsa_db.drop_all()
        self.app_context.pop()

    def test_app_exists(self):
        self.assertTrue(current_app is not None)
```

**Comment by epogrebnyak** [comment]
Refactoring in process at e36fbe06ed9e4f3f4bd1175375cc30b537915946

**Comment by epogrebnyak** [comment]
Tests refactoring finished by 7ed5bc3744a187157a993574c194e0224902aa2d

Model tests: <https://github.com/mini-kep/db/blob/master/tests/test_views.py>
