### ISSUE TITLE
add CSV serialiser and format parameter to /datapoints

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#11]
<https://github.com/mini-kep/helpers/blob/master/custom_api.py>

**Comment by SuperVasya** [comment]
Please approve da4b5e2ba2fe7a9b18feac67412dd772ce39f958

**Comment by epogrebnyak** [comment]
@SuperVasya 
- in browser newlines in csv response do not seen as newlines, we can try set line terminator to something that makes a csv render by row on screen and still be readable
```
import pandas as pd

df = pd.read_csv("https://minikep-db.herokuapp.com/api/datapoints?name=USDRUR_CB&freq=d&start_date=2017-08-01&end_date=2017-10-01&format=csv")
```

- I think csv should default arg, if we can achieve the above
- may have simplier test than the one with pandas

**Comment by SuperVasya** [comment]
@epogrebnyak 
commit 1f09b52
- It should be `<br>` since it's HTML output. It's compatible with pandas.read_csv()
- CSV is default
- Updated test, we get random datapoint from raw json data and check if it exists in output CSV

**Comment by epogrebnyak** [comment]
<https://github.com/mini-kep/db/issues/12> can we prevent html rendering in browser?

**Comment by epogrebnyak** [comment]
Closing in favour of #12, #13, #14.
