### ISSUE TITLE
can we prevent CSV output to be rendered as html in browser?

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#12]
When looking at the source of csv output I can see the orginal CSV file easily:

<view-source:https://minikep-db.herokuapp.com/api/datapoints?name=USDRUR_CB&freq=d&start_date=2017-08-01&end_date=2017-10-01>

...but in browser it gets rendered to html. Can we prevent html rendering in browser? What controls for it? some headers?

**Comment by epogrebnyak** [comment]
@SuperVasya: 
> We can return CSV response with csv mimetype `return Response(response_data, mimetype='text/csv')`, but in this case users won't be able to watch data in browser (since it's not HTML, browser will propose to save content to file)

**Comment by epogrebnyak** [comment]
``mimetype='text/csv'``` seems more appropriate, but Save as prompts are irritating. Myself also looking at <https://stackoverflow.com/questions/398237/how-to-use-the-csv-mime-type>

**Comment by epogrebnyak** [comment]
maybe ```Content-Disposition: inline``` is of some use to make txt reder in browser, and do not start save-as window

**Comment by SuperVasya** [comment]
@epogrebnyak Done in dc121d2f453bc4c6af4ead8366826eaf8ec43df9 `mimetype='text/plain'`

**Comment by epogrebnyak** [comment]
Shows in browser exactly right after dc121d2f453bc4c6af4ead8366826eaf8ec43df9!
