### ISSUE TITLE
validate freq, name and date parameters in \datapoints

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#13]
In [parameter handling](https://github.com/mini-kep/db/blob/master/db/api/views.py#L19-L24) we should have:

- ```freq``` must be certain letters, notify if not
-  if ```name``` not found at this given this frequency, notify
- check dates are valid:
  - end is after start
  - start is or before today 

Currently on all checks return ```[]```, bu that is a simplification.

**Comment by SuperVasya** [comment]
Implemented in bcb3e7df73e184535fa92c3576ba6e3cd9c19d33 and 73dc70e03ff5ad6e081a7c380ffa8b6ecc71c0eb. Examples:
- [wrong freq](https://minikep-db.herokuapp.com/api/datapoints?name=zxc&freq=z&format=json)
- [wrong name for such freq](https://minikep-db.herokuapp.com/api/datapoints?name=zxc&freq=q&format=json)
- [start date in future](https://minikep-db.herokuapp.com/api/datapoints?name=BRENT&freq=d&format=json&start_date=2018-01-01)
- [end date > start date](https://minikep-db.herokuapp.com/api/datapoints?name=BRENT&freq=d&format=json&start_date=2011-01-01&end_date=2000-01-01)

**Comment by epogrebnyak** [comment]
@SuperVasya - lets drop this check, it is a bit too restrictive: <https://minikep-db.herokuapp.com/api/datapoints?name=BRENT&freq=d&format=json&start_date=2018-01-01>, lets allow start date to be in the future, I need that for custom API to work.

**Comment by epogrebnyak** [comment]
Just as empellishment, maybe move the suggested list to ```'suggested': [...]``` in json? This may be practival to whoever uses the error response:
- wrong freq
- wrong name for such freq

**Comment by SuperVasya** [comment]
@epogrebnyak Done in bcb3e7df73e184535fa92c3576ba6e3cd9c19d33 and 73dc70e03ff5ad6e081a7c380ffa8b6ecc71c0eb

**Comment by epogrebnyak** [comment]
Had to restore *'start date in future'* test, I was wrong about excluding it.

**Comment by epogrebnyak** [comment]
@SuperVasya - lets do some eye review of ```util.py``` and close it, most functionality is already there.

**Comment by epogrebnyak** [comment]
I think we just need tests for this functionality as in <https://github.com/mini-kep/db/blob/master/README.md#parameter-errors>, otherwise it seems done to me.

**Comment by epogrebnyak** [comment]
May need some test refactoring at <https://github.com/mini-kep/db/blob/master/tests/test_views.py>, to be done under #10
