### ISSUE TITLE
work with flask model in stand-alone mode

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#16]
<https://github.com/mini-kep/db/blob/master/utils.py#L82-L120>

**Comment by epogrebnyak** [comment]
@SuperVasya , @relique - can you help me with this basic stuff? I run into problem describe both on django and flask: I try to work with it standalone and fail to set up a proper context.

**Comment by SuperVasya** [comment]
@epogrebnyak there's no such file database.
Add following lines
`from db import db`
`db.create_all(app=create_app('config.TestingConfig'))`
Or create db with the file `db_init.py`

**Comment by epogrebnyak** [comment]
Should we use such database in our tests too?

I think the test database should have some small dataset (D1), and also
another dataset (D2) for POST api/incoming test. I'll make the datasets.

12 окт. 2017 г. 14:19 пользователь "Eugene Karimov" <
notifications@github.com> написал:

**Comment by SuperVasya** [comment]
@epogrebnyak 
You need to run this code with app context:
```
    with app.app_context():
        db.init_app(app)
        possible_names_values = Datapoint.query.filter(Datapoint.freq == 'd') \
            .group_by(Datapoint.name) \
            .values(Datapoint.name)
        assert list(possible_names_values) == []
```

**Comment by epogrebnyak** [comment]
On existing dev database works like:

```python 
from db import create_app
    from db.api.views import api as api_module

    # create test app
    app = create_app('config.DevelopmentConfig') 
    app.register_blueprint(api_module)
    
    # EP: works without db creation after done once
    # from db import db
    # db.create_all(app=create_app('config.DevelopmentConfig'))
    # db.init_app(app)
    
    with app.app_context():
        possible_names_values = Datapoint.query.filter(Datapoint.freq == 'd') \
            .group_by(Datapoint.name) \
            .values(Datapoint.name)
        assert list(possible_names_values) == []
```
