### ISSUE TITLE
unit tests for SQLAlchemy database operations 

### ISSUE THREAD

**Issue by varnie** [mini-kep/db#2]
It is required to create a simple tests module for basic DB operations: create, read, update, delete (CRUD) utilizing SQLAlchemy SQL Toolkit.

**Comment by epogrebnyak** [comment]
I think *create* we are not testing as much.

Some links inspiring this work:

<https://pythonhosted.org/Flask-Testing/#testing-with-sqlalchemy>

and this:

<https://stackoverflow.com/questions/145131/whats-the-best-strategy-for-unit-testing-database-driven-applications>

We are not wrapping code in flask, yet, but after this excercise we want to implement RESTful wrapper for a database <https://flask-restless.readthedocs.io/en/stable/quickstart.html>. Tests developped under this issue will be used to test app too.

**Comment by epogrebnyak** [comment]
On previous commit:
- need non-Flask version, plain SQLAlchemy
- in tests ```__populate()``` must be an explicit setup

**Comment by epogrebnyak** [comment]
<https://github.com/mini-kep/db/blob/master/sqla_demo/clientdb.py> and <https://github.com/mini-kep/db/blob/master/tests/test_clientdb_demo.py> list the primitives needed for storage class.

Next:
- specifiy db usage requirements
- update primitives

**Comment by varnie** [comment]
hello, how are you? Is this resolved?
Thanks.

**Comment by epogrebnyak** [comment]
What is problem.you are facing?

**Comment by epogrebnyak** [comment]
Why spamming in issue title, @varnie - *ein zwei polizei* thing.
