### ISSUE TITLE
create simple data visualation with dash and boken libraries

### ISSUE THREAD

**Issue by Perevedko** [mini-kep/db#25]
Docs: https://plot.ly/dash/getting-started

**Comment by epogrebnyak** [comment]
For the vizualisation: 
- select frequency in radio buttons 
- select indicator by name in drop-down menu
- plot one line as time series

**Comment by epogrebnyak** [comment]
Frequency selection affects list of indicators

**Comment by epogrebnyak** [comment]
Choosing name affects plot

**Comment by epogrebnyak** [comment]
Make a page for the local server, then integrate into 'db' app

**Comment by epogrebnyak** [comment]
This is some interaction in bokeh  
<http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html#userguide-interaction-widgets>

**Comment by Perevedko** [comment]
dash graphs prototype: https://github.com/mini-kep/db/commits/dash

**Comment by zarak** [comment]
Here's the [bokeh graphs prototype](https://github.com/mini-kep/frontend-bokeh). I wasn't able to use radio buttons to update the frequencies via the callback, so I stuck with dropdown lists. I'll need to look into it some more.

Thanks @Perevedko for posting your dash script; it was helpful for me to get started with bokeh.

**Comment by epogrebnyak** [comment]
Cloing in favour of <https://github.com/mini-kep/frontend-dash/issues/3>
