### ISSUE TITLE
rename 'custom_api_blueprint.py'

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#29]
https://github.com/mini-kep/db/blob/21485a73299910182f228a01e38badbdc7fd384e/db/custom_api/custom_api_blueprint.py#L1

**Comment by epogrebnyak** [comment]
See also https://github.com/mini-kep/db/commit/c61fe92fbfea511378f53d812faf296b3ba19bba

**Comment by Perevedko** [comment]
https://github.com/mini-kep/db/commit/6d60f50518750a10b3f991668b6c24bd67e08f9d
