### ISSUE TITLE
buggy TokenHelper.__as_date

### ISSUE THREAD

**Issue by varnie** [mini-kep/db#30]
Hello everybody.

This link http://mini-kep.herokuapp.com/ru/series/GDP/a/yoy/12311111111111111111
produces:

> Internal Server Error
>
>The server encountered an internal error and was unable to complete your request. Either the server is >overloaded or there is an error in the application.

because TokenHelper.__as_date method is buggy.

Here's the relevant stacktrace:

> 127.0.0.1 - - [24/Oct/2017 16:26:24] "GET /ru/series/GDP/a/yoy/12311111111111111111 HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/varnie/thrash/my-virt-environments/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/varnie/thrash/projects/db/db/custom_api/views.py", line 22, in time_series_api_interface
>     return custom_api.CustomGET(domain, varname, freq, inner_path).get_csv_response()
>   File "/home/varnie/thrash/projects/db/db/custom_api/custom_api.py", line 180, in __init__
>     ip = InnerPath(inner_path)
>   File "/home/varnie/thrash/projects/db/db/custom_api/custom_api.py", line 141, in __init__
>     self.dates = helper.get_dates_dict()
>   File "/home/varnie/thrash/projects/db/db/custom_api/custom_api.py", line 73, in get_dates_dict
>     result['start_date'] = self._as_date(start_year, month=1, day=1)
>   File "/home/varnie/thrash/projects/db/db/custom_api/custom_api.py", line 107, in _as_date
>     day=day).strftime('%Y-%m-%d')
> OverflowError: Python int too large to convert to C long

Also, not sure whether it is relevant or not, but the following link:
https://minikep-db.herokuapp.com/api/datapoints?name=BRENT&freq=d&start_date=2017-01-01
also produces:

> Internal Server Error
>
>The server encountered an internal error and was unable to complete your request. Either the server is >overloaded or there is an error in the application.

(I've taken this link from the README.MD: http://joxi.ru/J2b57NMiXJWWLm )

Thank you for your time.

**Comment by epogrebnyak** [comment]
Not sure this is intended use, but definitely better catch this in date processing.

**Comment by varnie** [comment]
If the 2nd provided link is not an example of intended usage, then why is it present at the README.MD  on the repo's frontpage?

**Comment by epogrebnyak** [comment]
Not sure where the problem is, you provided different links for in the message and in readme:
- <http://mini-kep.herokuapp.com/ru/series/GDP/a/yoy/12311111111111111111> - this is not even in this dyno,there is not intent to use it like this with ```12311111111111111111```. 
- <https://minikep-db.herokuapp.com/api/datapoints?name=BRENT&freq=d&start_date=2017-01-01>
is actually faulty, which is more severe.

**Comment by epogrebnyak** [comment]
This is actally two issues, right?

**Comment by varnie** [comment]
Maybe, I am not sure, it needs debugging.

**Comment by epogrebnyak** [comment]
Proper link to this dyno is:
<http://minikep-db.herokuapp.com/ru/series/GDP/a/yoy/12311111111111111111>
