### ISSUE TITLE
http://mini-kep.herokuapp.com/ru/series/HELLO/BUDDY Internal Server Error

### ISSUE THREAD

**Issue by varnie** [mini-kep/db#33]
Good evening.

http://mini-kep.herokuapp.com/ru/series/HELLO/BUDDY

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Thank you for your time.

**Comment by epogrebnyak** [comment]
@varnie -  for the etiquette

> Good evening.
> Thank you for your time.

Not neeeded, tetle, + problem specification are qute enough.

**Comment by varnie** [comment]
@epogrebnyak please don't explain to me how to greet people.

**Comment by epogrebnyak** [comment]
Not in the issues, it it reduntant here.

24 окт. 2017 г. 22:17 пользователь "varnie" <notifications@github.com>
написал:
