### ISSUE TITLE
specification for datapoint db

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#4]
In [this pipline](https://github.com/mini-kep/intro/blob/master/pipeline/pipeline.py), we have the following situation:

- the parser can deliver a list of dicts, each dict is a datapoint
- the database should have a POST method to ```api\incoming``` to write incoming json to db
- the POST operation shoudl have some authentication
- we simplify the rules for now and all data is upserted (newer data overwrites older)
- the database has GET method styled around the datapoint key (variable name, frequency, start date and end date)
- the GET operation is public API

@SuperVasya: please extend questions/descriptions. 

At this issue we want:
- [ ] description of db methods (based on above)
- [ ] descritpion of incoming/outgoing data
- [ ] list options to implemet (eg flask+sqlalchemy+heroku+postgres)
- [ ] ideally, how to test this (in words/pseudocode)

**Comment by epogrebnyak** [comment]
Incoming data is a list of dicts like ```dict(date="2014-03-31", freq='q', name="CPI_rog", value=102.3)```.
- a large (1.8M) json with such data is [located here](https://github.com/mini-kep/intro/blob/master/pipeline/pipeline.py)
- sample data is presented [here](https://github.com/mini-kep/full-app/issues/9#issuecomment-331814995)
- and it all orginates from ```Dataset.yield_dicts()```/ ```Dataset.serialise()``` at  aroudn <https://github.com/mini-kep/parsers/blob/master/parsers/runner.py#L149-L151>

**Comment by SuperVasya** [comment]
- For POST authentication I think the best option is using token which will be stored in environment variables (Heroku config vars), when client tries to POST data, it should send this token in request's header or pass as parameter.

- [ ] Scheduler for updating data

**Comment by epogrebnyak** [comment]
> Scheduler for updating data
Can you put your wording about the scheduler? it is outside of this scope, but useful to understand the context.

**Comment by SuperVasya** [comment]
> Scheduler for updating data
> Can you put your wording about the scheduler? it is outside of this scope, but useful to understand the context.
Since we don't use any physical or virtual machines, it's possible to implement it with Celery (but it my opinion it's overkilling for this purpose)
For Heroku the best option is to use their APScheduler
https://devcenter.heroku.com/articles/clock-processes-python

**Comment by SuperVasya** [comment]
1)	Tech stack:
Web-frameworks: Flask, Django + SQLAlchemy (deployed to Heroku)
Database: Postgres (Heroku or AWS)
Scheduler (for periodic database updates): Heroku APS https://devcenter.heroku.com/articles/clock-processes-python

2)	Database schema:
Id – UID, autoincrement
Date – type DateTime
Freq – type String
Name – type String
Value – Float

3)	Following methods should be available
3.1)	GET /API/`<id>` - get data about an entity
Method returns error 404 if there’s no such ID
Method return error 400 if ID is not Integer
3.2)	GET / API/values with following URL parameters:
fromDate – should return results with date greater than this parameter
toDate – should return results with date less than this parameter
Freq – list of freq values to return like freq=a,b,c,d
Name – list of name values to return like name=a,b,c,d
fromValue - should return results with value greater than this parameter
toValue - should return results with value less than this parameter. <br>
Method returns JSON with data or empty JSON if there’s no data with such query.
Method validates parameters and returns error 400 if there’s an error in parameters (like string in data parameter or empty parameter) <br>
3.3)	POST /API/`<id>`
Update data with following ID with values in request body.
Body should have a structure like
    {
        "date": "1999-01-31",
        "freq": "m",
        "name": "INVESTMENT_rog",
        "value": 12345.6
    } 
<br>Only updating fields are inside request’s body. Never pass ID inside it.
Method validates values, return error 400 if there’s an error in parameters ((like string in data parameter or empty parameter or ID is not Integer)
Method return error 404 if there’s no such ID.
Method returns empty JSON on success.<br>
3.4)	POST /API/new
Insert new data with values in request body.
Body should have the same structure as in method 3.3.
All fields should be filled.
Never pass ID inside request body.
Method validates values, return error 400 if there’s an error in parameters (like string in data parameter or empty parameter or missing field)
Method returns empty JSON on success.<br>
4)	Tests.
Upload data from JSON to DB, run python unit tests with requests to different methods, validate them with uploaded data.
Use combinations GET – POST – GET to validate data inserts and updates.<br>
5)	Security.
POST methods should require API_TOKEN as URL parameter or header, validate it with environment variable (Heroku config vars)

**Comment by epogrebnyak** [comment]
These comments are summarised in <https://github.com/mini-kep/db/blob/master/SPEC.md>, will open a new issue to review this document.
