### ISSUE TITLE
DELETE method for datapoints

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#45]

**Comment by ignaloidas** [comment]
So there should be a route that deletes some datapoint by title or unit?

**Comment by epogrebnyak** [comment]
@ignaloidas, was it you who introdiced a delete endpoint? are you realising this is a bit on nonsense?
 
https://github.com/mini-kep/db/blob/3cec7d06bcf62875e95a1f4b2e7701f085eeef17/tests/test_views.py#L219-L241
