### ISSUE TITLE
list other test parametrisations 

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#77]
Need a list of other test parametrisations - something to select from to do next

**Comment by vasmitr** [comment]
1. Test_TokenHelper_year_handling in test_decomposer.py
2. test_get_start_end_date_for_CPI_NONFOOD_rog_returns_proper_dates in test_views.py
3. test_get_on_name_and_freq_returns_list_of_dicts in test_views_datapoints.py
4. test_on_name_delete_successfull_200 in test_views_datapoints.py

**Comment by epogrebnyak** [comment]
@vasmitr - how about markdown links to code?

**Comment by vasmitr** [comment]
1. https://github.com/mini-kep/db/blob/b8263221c6d46416aee59179f719fabeb01c0d8e/tests/custom_api/test_decomposer.py#L51-L61
2. https://github.com/mini-kep/db/blob/b8263221c6d46416aee59179f719fabeb01c0d8e/tests/test_views.py#L45-L49
3. https://github.com/mini-kep/db/blob/b8263221c6d46416aee59179f719fabeb01c0d8e/tests/test_views_datapoints.py#L78-L83
4. https://github.com/mini-kep/db/blob/b8263221c6d46416aee59179f719fabeb01c0d8e/tests/test_views_datapoints.py#L142-L146
5. https://github.com/mini-kep/db/blob/b8263221c6d46416aee59179f719fabeb01c0d8e/db/api/queries.py#L194-L197
