### ISSUE TITLE
API extensions

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#8]
- ```api/datapoints/varnames/{freq}``` lists all variable names available as that frequency ```{freq}``` (assumed to be in ```aqmwd```)
- variable descriptions ```GDP``` -> ```Gross domestic product```
- use [unit descriptions](https://github.com/mini-kep/parser-rosstat-kep/blob/master/src/csv2df/specification.py#L74-L84)
- [varname splitter](https://github.com/mini-kep/parser-rosstat-kep/blob/master/src/csv2df/util_label.py) goes to helper function, will need to use it locally

**Comment by epogrebnyak** [comment]
## Time series identifiers (``CPI_yoy``` and ```GDP_rog```):
- ```api/names/all``` - list all available ```names``` appearing at least at some frequency
- ```api/names/{freq}``` - list all available ```names``` at ```{freq}```, example:  ```api/names/a```

## Varnames (```GDP```, ```CPI```):
-  ```api/varnames/all``` - will list heads of variable names like ```GDP```, ```CPI```

## Varname description 
-  ```api/varnames/description/{varname}&lang={?lang}```

     Example:
     api/description/en/GDP returns ```Gross domestic product```

- will rely on [varname splitter](https://github.com/mini-kep/parser-rosstat-kep/blob/master/src/csv2df/util_label.py).
- will need extra table in database

## Same for units 
- all units
- unit description

**Comment by epogrebnyak** [comment]
@SuperVasya - can we plann this as addition to API at some point of time?

**Comment by SuperVasya** [comment]
@epogrebnyak 
- ```api/names/all``` - list all available ```names``` appearing at least at some frequency
- ```api/names/{freq}``` - list all available ```names``` at ```{freq}```, example:  ```api/names/a```

I can start to work on this methods now, we don't need any additional data or anything else for it.

For other methods (varnames, varname description, units, unit description) we need an additional table with data, right?

**Comment by epogrebnyak** [comment]
Right, the /names/ method is based on existing data, the other methods need
extra data (and possibly some agreed procedure to import it, maybe POST
method too). Can implement /names/ in due course.

As for priorities, we need csv serialiser before /names/.

10 окт. 2017 г. 21:37 пользователь "Eugene Karimov" <
notifications@github.com> написал:

**Comment by epogrebnyak** [comment]
## info method

```api/info?name={name}&freq={freq}``` should return a json with start and end dates (to edit)

**Comment by epogrebnyak** [comment]
NOT TODO:

0. with splitter method: query all varheads
- /names/all/?head=CPI 
- /names/q/?head=CPI 
- /names/q/?startswith=CPI

1. with splitter method:
- ```split?name={name}``` (splits name to VARNAME and unit)

2. with extra data (descriptions) - can be used to make 
- ```description/?varname={varname}``` (can be used )
- ```description/?unit={unit}&lang={lang}```

3. with extra data (sections):
- ```sections/``` - return dictionary ```{section:[list]}```

4. more is added to info method:
- varhead
- unit
- var_desc
- unit_desc

5. graphics methods

**Comment by epogrebnyak** [comment]
NOT TODO:
- allow multiple names, comma-separated in the /database call
- allow /preset/freq/?name=<name>, where name is 'all' or section name

**Comment by epogrebnyak** [comment]
```api/freq``` - list available frequencies with names
