### ISSUE TITLE
api/datapoints must raise exception on wrong format argument

### ISSUE THREAD

**Issue by vasmitr** [mini-kep/db#85]
Now if we do request with for example format=html, we'll get csv response. It's unexpected behavior.
Also DatapointAPI view checks args itself, but validation must be moved to parameters.py.
https://github.com/mini-kep/db/blob/f77b0d3ce8bee4bcd8992eb81181486b6078ebda/db/api/views.py#L98-L103

**Comment by epogrebnyak** [comment]
@vasmitr - is this fixed?

**Comment by epogrebnyak** [comment]
@vasmitr - what should be done about this branch?
