### ISSUE TITLE
review custom api

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#86]
- [ ] are there any links that are expected to work, but not working?
- [ ] are there any unexpected behaviours?
- [ ] should tests be changed/parametrised?
- [ ] should [API description](https://github.com/mini-kep/db/blob/master/CUSTOM_API.md) be changed?

**Comment by Perevedko** [comment]
- are there any links that are expected to work, but not working?

no

- are there any unexpected behaviours?

i think https://github.com/mini-kep/db/issues/85 is unexpected behaviour

- should tests be changed/parametrised?

https://github.com/mini-kep/db/blob/master/tests/custom_api/test_decomposer.py contains a lot of commented code, should it be used or deleted?

- should [API description](https://github.com/mini-kep/db/blob/master/CUSTOM_API.md) be changed?

slightly, currently api description has wrong link
<https://minikep-db.herokuapp.com/ru/series/GDP_yoy/q/2016-01-01>
should be changed to
<https://minikep-db.herokuapp.com/ru/series/GDP_yoy/q/2016>

**Comment by epogrebnyak** [comment]
Closed in favour of #87
