### ISSUE TITLE
merge custom API to 'db' repo

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#9]
Can we mount custom API in *db* project too? See <https://github.com/mini-kep/helpers/issues/3> and <https://github.com/mini-kep/frontend-app/blob/master/apps/views/time_series.py>

**Comment by epogrebnyak** [comment]
Not todo until discussed at <https://github.com/mini-kep/helpers/issues/13>

**Comment by Perevedko** [comment]
proposed steps:
1. create a branch "merging-custom-api"
2. copy `helper-custom-api/src/custom_api.py -> db/db/api/custom_api.py`
3. copy `helper-custom-api/src/test_custom_api.py -> db/tests/test_custom_api.py`
4. change import path in tests
5. https://github.com/mini-kep/db/blob/master/db/api/views.py#L22: separate logic from view -- create `db/db/api/controllers.py` and create `datapoints` function which will contain logic code from `views.get_datapoints `
6. change `views.get_datapoints` so that it will use `controllers.datapoints`
7. create a blueprint for `custom_api` that will use `controllers.datapoints` too
8. register blueprint in app

**Comment by epogrebnyak** [comment]
В принципе согласен, комментарии:
- controllers.py - контроллер обычно что-то меняет в модели, у нас это просто часть запроса. нужно какое-то другое название файла, controllers.py не подходит. Не знаю насколько принято, но может в model.py эти функции запросов записать? 
- *create a blueprint for custom_api that will use controllers.datapoints too* blueprint же регистрирует view, он точно еще и контроллер должен регистрировать?
- есть риск конфликта имен custom API и других api, нужен комментарий по этому поводу.

Считаю надо разбить на более мелкие шаги, сразу 7 пунктов зависнут/могут пойти непраивльно. @Perevedko - можете подумать над независимыми этапами, которые можно проверить? что-то типа рефакторинга сущесвтующего кода ```db/db``` (этап 1) + добавление custom API (этап 2), как пример.

**Comment by Perevedko** [comment]
> controllers.py - контроллер обычно что-то меняет в модели, у нас это просто часть запроса. нужно какое-то другое название файла, controllers.py не подходит. Не знаю насколько принято, но может в model.py эти функции запросов записать?

можно и в модель staticmethod запихнуть, разница невелика будет

> create a blueprint for custom_api that will use controllers.datapoints too blueprint же регистрирует view, он точно еще и контроллер должен регистрировать?

нет, блюпринт будет использовать функцию

> есть риск конфликта имен custom API и других api, нужен комментарий по этому поводу.

можно использовать префикс для блюпринта. /customapi, например.

**Comment by epogrebnyak** [comment]
По endpoint: /customapi не очень подойдет, потому что url должен быть максимально коротким
можно пожертвоввать исходным дизайном и сделать ```minike-db.herokuapp.com/series/<domain>``` - так возможно проблем меньше будет.

**Comment by epogrebnyak** [comment]
разделение ```get_datapoints()``` в [views.py](https://github.com/mini-kep/db/blob/master/db/api/views.py#L21-L59): может чтобы далеко не ходить в самом views.py разделим?

**Comment by Perevedko** [comment]
сделаю в views следующие функции:

`validate_and_transform_datapoints_params`
валидирует параметры и трансформирует

`perform_datapoints_query`
выполняет запрос по параметрам

`collect_datapoints`
вызывает две вышеописанные функции, то есть, сначала валидирует и трансформирует параметры, потом выполняет запрос

**Comment by epogrebnyak** [comment]
первый две делаем, третья ```collect_datapoints``` непонятно зачем нужна - где надо и так две первые вызовем

**Comment by epogrebnyak** [comment]
Если разносить эти функции потом из ```views.py```, то первая идет в utils.py, вторая в model.py

**Comment by Perevedko** [comment]
https://github.com/mini-kep/db/commit/f5e1c88cfc152722946eecb17314b8bac77e302f

**Comment by epogrebnyak** [comment]
Not todo, just a note for myself: ```util.DatapointParameters(args, exception=...).get()``` - pack parse and validate parameters for datapoints.

**Comment by Perevedko** [comment]
step 2: merging custom api

1. create a branch "merging-custom-api"
2. copy helper-custom-api/src/custom_api.py -> db/db/api/custom_api.py
3. copy helper-custom-api/src/test_custom_api.py -> db/tests/test_custom_api.py
4. change import path in tests
5. create a blueprint: db/db/api/custom_api_blueprint
6. register blueprint in app

**Comment by epogrebnyak** [comment]
Lets finish step 1 before doing 2

17 окт. 2017 г. 18:16 пользователь "Perevedko" <notifications@github.com>
написал:

**Comment by Perevedko** [comment]
_get_datapoints:
https://github.com/mini-kep/db/commit/579b6802e2a42438f89a45f024bcb1a959667357

**Comment by epogrebnyak** [comment]
Great, lets have some minimal tests for the new functions

17 окт. 2017 г. 18:36 пользователь "Perevedko" <notifications@github.com>
написал:

**Comment by Perevedko** [comment]
tests: https://github.com/mini-kep/db/commit/d4bc2e0a507dfe3f820099dd34f810696b59934e

**Comment by epogrebnyak** [comment]
Will edit the tests, please review after I commit.

**Comment by epogrebnyak** [comment]
@Perevedko: Lets focus on what custom API transfer

- [ ] create a branch "dev-custom-api"
- [ ] make folder db/custom_api
- [ ] copy files:  
    - copy helper-custom-api/src/custom_api.py -> db/db/custom_api/custom_api.py
    - copy helper-custom-api/src/test_custom_api.py -> db/tests/test_custom_api.py
    - change import path in tests
 - [ ] integrate 
   - create a blueprint: db/db/api/custom_api_blueprint
   - register blueprint in app
- [ ] write small samples of custom api calls to README.md

```
    http://minikep-db.herokuapp.com/oil/series/BRENT/d/2017/
    http://minikep-db.herokuapp.com/ru/series/CPI_rog/m/2000/2010
    http://minikep-db.herokuapp.com/ru/series/GDP/a/yoy/1998/2017
```

**Comment by Perevedko** [comment]
https://github.com/mini-kep/db/commits/dev-custom-api

**Comment by epogrebnyak** [comment]
Finishing integration:
- symmetric naming  - FIXME in <https://github.com/mini-kep/db/blob/master/db/custom_api/custom_api_blueprint.py>

**Comment by epogrebnyak** [comment]
closed in favour of #28 and #29
