### ISSUE TITLE
new field for Datapoint (db migration and associated tasks)

### ISSUE THREAD

**Issue by Perevedko** [mini-kep/db#90]
Idea is to show same variables for different countries. For example - ru-CPI, kz-CPI (Inflation in Russia and Kazakhstan). 
Currently, custom api has a reserved `domain` field.
TODO
- [x] Add alembic to project
- [ ] Write a migration that adds (and update the model) string field `domain` to `Datapoint` model. For existing datapoints, it should be = `ru`, except for Brent (`oil`) and UST (`us`).
- [ ] Add heroku hook for db automatic migration - <https://devcenter.heroku.com/articles/release-phase>
- [ ] Change custom api behaviour to use `domain` 

Предложения:
- [ ] Понадобится еще одна таблица с разрешенными доменами Domain, одно поле строка + индекс
- [ ] Нужно проверять POST datapoints на правильность домена

**Comment by epogrebnyak** [comment]
Our end-user case is that at least some variabels can have same name for different countriesr, for example - inflation in Russia and Kazakhstan should be denoted as `ru` and `CPI`, `kz` and `CPI`. To achive this we need changes in database schema, GET methods and other methods. This issue is to discuss these changes.

**Comment by epogrebnyak** [comment]
End user perspective:
- `GET datapoints`: `domain` arg is added to query or to `datapoints\ru` 
- custom api GET has reserved position for domain
- `GET frame`: allow `ru:CPI,GDP`, `oil:BRENT`, `ru,cn,br,sa:CPI`?

**Comment by Perevedko** [comment]
working branch: https://github.com/mini-kep/db/commits/dev-db-migration-90

**Comment by epogrebnyak** [comment]
Database:
- change schema - add string nullable `country` field to Datapoints
- this field is not none on country data, but it is none on global data as BRENT, UST*, or even USDRUR - the reason for this is is that these variables will not be mixed with country data and they will appear in any domain
- `country` need its own table

**Comment by epogrebnyak** [comment]
Parsers:
 - may have a `country` field on output
