### ISSUE TITLE
Custom API: `info` finaliser

### ISSUE THREAD

**Issue by Perevedko** [mini-kep/db#91]
In custom api, `info` is reserved word for finaliser.
We have `api/info` method.
If finaliser `info` is chosen in custom api, result from `api/info` should be returned.

**Comment by epogrebnyak** [comment]
- [ ] need a test that read url like <http://minikep-db.herokuapp.com/ru/series/EXPORT_GOODS/m/bln_usd/info> or  <http://minikep-db.herokuapp.com/ru/series/EXPORT_GOODS_bln_usd/m/info>

**Comment by epogrebnyak** [comment]
@lynxrv21 : what happens if there are two finalisers? eg `xlsx` and `info`

**Comment by lynxrv21** [comment]
@epogrebnyak seems like last one wins:  `.../xlsx/info` will show variable info and `.../info/xlsx` shows data

**Comment by epogrebnyak** [comment]
Current design now separates splitting of inner path and finding ```info``` finaliser in route.  
A cleaner way is to fail with error when two finalisers are specified, but lets do that later.
