### ISSUE TITLE
create tests for `api/desc`

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#92]
https://github.com/mini-kep/db/blob/555b26cc04ca4195d0d5c68ea6e29297b5d62e37/integration/desc.py#L1-L25

**Comment by epogrebnyak** [comment]
See new specification of the tests here:
<https://github.com/mini-kep/db/blob/master/integration/desc.py>

**Comment by lynxrv21** [comment]
- [ ] Review similar branches [dev-api-desc-tests-92](https://github.com/mini-kep/db/tree/dev-api-desc-tests-92), [dev-api-desc-93](https://github.com/mini-kep/db/tree/dev-api-desc-93)
- [ ] Migrate tests from `requests` to flask `test_client`
- [ ] Remove vars names from tests

**Comment by epogrebnyak** [comment]
The branches to review are:
- dev-desc-tests-92
- https://github.com/mini-kep/db/tree/dev-api-desc-tests-92

I suggest https://github.com/mini-kep/db/tree/dev-api-desc-tests-92 gets deleted.

**Comment by epogrebnyak** [comment]
@lynxrv21 : dev-api-desc-93 is a brach for different issue

**Comment by epogrebnyak** [comment]
Merged branches to https://github.com/mini-kep/db/tree/dev-desc-tests-92

**Comment by epogrebnyak** [comment]
Current workfile: https://github.com/mini-kep/db/blob/dev-desc-tests-92/tests/test_view_desc.py

**Comment by epogrebnyak** [comment]
I think DELETE method requires more setup, must post data forst before delete.
